import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { BUILDINGS } from '../data/buildings';
import { OVENS, RARITY_COLORS } from '../data/ovens';
import { useGameStore } from '../store/useGameStore';

const fmt=(n:number)=>Math.floor(n).toLocaleString('ko-KR');
const Button=({title,onPress,disabled=false}:{title:string;onPress:()=>void;disabled?:boolean})=><Pressable disabled={disabled} onPress={onPress} style={[s.button,disabled&&s.disabled]}><Text style={s.buttonText}>{title}</Text></Pressable>;
const Page=({title,children}:{title:string;children:React.ReactNode})=><ScrollView contentContainerStyle={s.page}><Text style={s.title}>{title}</Text>{children}</ScrollView>;
export function DrawPage(){const game=useGameStore();const run=(premium=false,count=1)=>{for(let i=0;i<count;i++)if(!game.draw(premium))break;};return <Page title="🎰 오븐 뽑기"><View style={s.hero}><Text style={s.heroText}>모든 등급의 오븐이 뽑기에서 등장합니다</Text><Text style={s.balance}>🍫 {fmt(game.chocoChips)} · 💎 {fmt(game.premiumChips)}</Text></View><Text style={s.section}>기본 초코칩 뽑기</Text><View style={s.row}><Button title="1회 뽑기" onPress={()=>run(false)}/><Button title="10회 뽑기" onPress={()=>run(false,10)}/></View><Text style={s.section}>프리미엄 초코칩 뽑기</Text><View style={s.row}><Button title="1회 뽑기" onPress={()=>run(true)}/><Button title="10회 뽑기" onPress={()=>run(true,10)}/></View><Text style={s.section}>등장 오븐</Text>{OVENS.map(o=><View key={o.id} style={[s.oven,{borderColor:RARITY_COLORS[o.rarity]}]}><Text style={s.ovenName}>{o.name}</Text><Text style={{color:RARITY_COLORS[o.rarity],fontWeight:'900'}}>{o.rarity==='Secret'?'???':o.rarity}</Text></View>)}</Page>}
export function AutomationPage(){const game=useGameStore();return <Page title="🏭 자동화"><Text style={s.info}>자동화 오븐은 초당 쿠키를 생산합니다. 판매 시 구매가의 80%를 돌려받습니다.</Text>{BUILDINGS.map(b=>{const count=game.buildings[b.id]||0;const cost=Math.floor(b.baseCost*Math.pow(1.15,count));return <View key={b.id} style={s.card}><Text style={s.cardTitle}>{b.emoji} {b.name}</Text><Text style={s.info}>보유 {count}개 · 초당 {fmt(b.baseCps*count)}</Text><View style={s.row}><Button title={`${fmt(cost)} 구매`} onPress={()=>game.buyBuilding(b.id)}/><Button title="판매" disabled={!count} onPress={()=>game.sellBuilding(b.id)}/></View></View>})}</Page>}
export function ExchangePage(){const game=useGameStore();return <Page title="💱 교환소"><Text style={s.info}>100,000 쿠키를 초코칩 1개로 교환합니다.</Text><View style={s.card}><Text style={s.cardTitle}>🍪 → 🍫</Text><Text style={s.info}>보유 쿠키 {fmt(game.cookies)}</Text><View style={s.row}><Button title="1개 교환" onPress={()=>game.exchangeCookies(100000)}/><Button title="10개 교환" onPress={()=>game.exchangeCookies(1000000)}/><Button title="전부 교환" onPress={()=>game.exchangeCookies(game.cookies)}/></View></View></Page>}
export function InventoryPage(){const game=useGameStore();return <Page title="🎒 인벤토리"><View style={s.hero}><Text style={s.balance}>🍪 {fmt(game.cookies)}</Text><Text style={s.balance}>🍫 {fmt(game.chocoChips)} · 💎 {fmt(game.premiumChips)}</Text></View><Text style={s.section}>오븐 컬렉션</Text>{game.ovens.filter(x=>x.level>0).map(x=>{const o=OVENS.find(v=>v.id===x.ovenId)!;return <Pressable key={o.id} onPress={()=>useGameStore.setState({equippedOvenId:o.id})} style={[s.oven,{borderColor:RARITY_COLORS[o.rarity]}]}><Text style={s.ovenName}>{game.equippedOvenId===o.id?'장착됨 · ':''}{o.name}</Text><Text style={s.info}>레벨 {x.level} · 클릭 x{o.click}</Text></Pressable>)}</Page>}
const s=StyleSheet.create({page:{padding:18,gap:12,backgroundColor:'#f8eed7'},title:{fontSize:28,fontWeight:'900',color:'#401923'},section:{fontSize:20,fontWeight:'900',color:'#401923',marginTop:8},hero:{backgroundColor:'#e2f1ff',borderRadius:22,padding:18,borderWidth:2,borderColor:'#bfd7ef',gap:6},heroText:{fontSize:16,fontWeight:'700',color:'#4b5663'},balance:{fontSize:18,fontWeight:'900',color:'#401923'},card:{backgroundColor:'#fff8e9',borderRadius:20,padding:16,gap:8,borderWidth:2,borderColor:'#d9bd85'},cardTitle:{fontSize:19,fontWeight:'900',color:'#401923'},info:{fontSize:14,fontWeight:'700',color:'#6a5a50'},row:{flexDirection:'row',gap:8,flexWrap:'wrap'},button:{backgroundColor:'#ffca45',borderRadius:14,paddingHorizontal:13,paddingVertical:11,flexGrow:1,alignItems:'center'},disabled:{opacity:.4},buttonText:{fontWeight:'900',color:'#401923'},oven:{backgroundColor:'#fff',borderLeftWidth:6,borderRadius:14,padding:13,gap:3},ovenName:{fontSize:16,fontWeight:'900',color:'#401923'}});
